### ISSUE TITLE
How to upgrade zigbee2mqtt app?

### ISSUE THREAD

**Issue by tebra-jl** [paxswill/iocage-zigbee2mqtt#3]
Hi all,
@paxswill 
I use this iocage and it works very well.
Now there is a new version of zigbee2mqtt but I can’t find instructions to upgrade from inside the jail?
Thanks

**Comment by paxswill** [comment]
Sorry, should document that better. Here's the process, done from within the jail:

1. Stop the service: `service zigbee2mqtt stop`
2. Change directories to the checkout: `cd /opt/zigbee2mqtt`
3. Pull latest from git (the default branch is also the release branch): `git pull`
4. Update the app and it's dependencies: `npm ci --production`
5. Start the service: `service zigbee2mqtt start`

I'm going to leave this issue open as a reminder to myself to document + make this a little easier.
